on: [push, pull_request]

name: Build and Test

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: cargo clippy -- -D warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo install cargo-sync-readme
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-sync-readme

      - name: cargo sync-readme --check (gcloud-ctx)
        run: |
          cd gcloud-ctx
          cargo sync-readme --check
          echo "gcloud-ctx README is correct"
          cd -

      - name: cargo sync-readme --check (gctx)
        run: |
          cd gctx
          cargo sync-readme --check
          echo "gctx README is correct"
          cd -

  test:
    name: Test Suite
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
