name: Build and Test

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose
